services:
  torch_api:
    build: ./ML
    container_name: torch_api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --reload-include *
    ports:
      - 8000:8000
    volumes:
      - ./ML:/app
  front_back_end:
    build: ./FrontEnd
    container_name: streamlit_app
    command: streamlit run app.py --server.port 8001 --server.address 0.0.0.0
    ports:
      - 8001:8001
    volumes:
      - ./FrontEnd:/app
  redis:
    build: ./Redis
    container_name: redis_container
    ports:
      - 6379:6379
    volumes:
      - ./Redis:/data